---
- hosts: peering-routers
  gather_facts: false
  connection: local

  tasks:
  - name: update prefix-list "{{ prefixlist_name }}"
    vars:
      prefixlist_name: prefix-list-test
    import_role:
      name: ios-prefix-list

  - name: apply prefix-list "{{ prefixlist_name }}" on route-map "{{ routemap_name }}"
    vars:
      prefixlist_name: prefix-list-test
      routemap_name: route-map-test
    import_role:
      name: ios-route-map
